Implement 'Create a Cluster' and 'Delete a Cluster' API
cloud-barista/cb-ladybug pull request #6
Opened 2020-10-16 12:16 UTC by itnpeople

### 작업내용

* [x] 단일 CSP 대상 클러스터 생성 
* [x] 단일 CSP 대상 클러스터 삭제
* 이슈 :#3, #5

### 이슈/제약사항/TODO/공유

* CSP AWS, GCP로 한정
* ControlPlane 노드수는 1개로 고정, //TODO HA 구성에 대한 검토&반영
* CSP별 Image 하드코딩, //TODO 코드화
* Connction Info. 하드코딩 (prefix: cb-aws, cb-gcp),  //TODO 멀티클라우드 처리방식 정의
* 현재 CSP를 구분할 방법이 없어 namespace 명으로 구분하도록 하였음
* 프로비저닝 시간 단축 필요성, //TODO 개선방안 검토
* 생성 중 하나의 노드가 실패했을 경우 - 재시도 방법

2020-10-19 04:34 UTC, seokho-son commented
제가 log 꼬인거 살짝 수정해보겠습니다.. ^^

2020-10-19 05:24 UTC, jihoon-seo commented on docs/design/entity.md
> +        role: "control-plane",
@itnpeople @sykim-etri @seokho-son 
`role: "control-plane"` 이라고 쓰는 것과
`role: "master"` 라고 쓰는 것 중
어느 쪽이 적절하려나요..?

(L31 에는 `role: "worker"` 라고 적혀 있음)

2020-10-19 05:31 UTC, jihoon-seo commented on docs/test/README.md
> +▒  docker run -d -p 1323:1323 --name cb-tumblebug --link cb-spider:cb-spider cloudbaristaorg/cb-tumblebug:v0.2.0-20200715
이렇게 바꾸는 것은 어떨까요?

```suggestion
▒  docker run -d -p 1024:1024 --name cb-spider cloudbaristaorg/cb-spider:v0.x.0-yyyymmdd
▒  docker run -d -p 1323:1323 --name cb-tumblebug --link cb-spider:cb-spider cloudbaristaorg/cb-tumblebug:v0.x.0-yyyymmdd
(각 컨테이너 이미지의 최신 tag는 다음을 참조:)
- https://hub.docker.com/r/cloudbaristaorg/cb-spider/tags
- https://hub.docker.com/r/cloudbaristaorg/cb-tumblebug/tags
```

2020-10-19 05:45 UTC, sykim-etri commented on docs/test/README.md
> +▒ brew install jq
Linux(ubuntu)인 경우의 설치 명령도 추가 부탁드립니다.
sudo apt-get install jq

2020-10-19 05:55 UTC, sykim-etri commented
sunmi님의 메일 주소가 github 계정과 연결되어 있지 않은 것으로 보입니다. 혹시 github 계정을 생성하셔서 활동하시는 것이 문제가 될까요?

2020-10-19 06:03 UTC, seokho-son commented
@itnpeople @sykim-etri 
해당 PR은 ladybug 저장소의 현재 master 브랜치로 rebase 되지 않은 상태로 작업된 것으로 보입니다.

제가 PR (itnpeople:master) 를 내려 받아서, 
기존 master 브랜치로 rebase 하였습니다.
Rebase 과정에 여러 File들에 Confilct가 발생하여서, 제가 이번 PR의 최종 형상이 되도록
메뉴얼 머지를 진행하였습니다.

따라서, 혹시 PR에 문제가 없는지 @itnpeople 께서 한번 확인해 보시는 것이 좋습니다.

2020-10-19 06:20 UTC, seokho-son commented
son@son:~/go/src/github.com/cloud-barista/cb-ladybug$ grep -r ">>>>>>> Add base source code"
docs/design/entity.md:>>>>>>> Add base source code
docs/design/entity.md:>>>>>>> Add base source code
docs/design/README.md:>>>>>>> Add base source code
docs/design/README.md:>>>>>>> Add base source code
docs/design/init-mcir.puml:>>>>>>> Add base source code

son@son:~/go/src/github.com/cloud-barista/cb-ladybug$ grep -r "<<<<<<< HEAD"
docs/design/entity.md:<<<<<<< HEAD
docs/design/entity.md:<<<<<<< HEAD
docs/design/entity.md:<<<<<<< HEAD
docs/design/entity.md:<<<<<<< HEAD
docs/design/entity.md:<<<<<<< HEAD
docs/design/entity.md:<<<<<<< HEAD
docs/design/entity.md:<<<<<<< HEAD
docs/design/entity.md:<<<<<<< HEAD
docs/design/entity.md:<<<<<<< HEAD
docs/design/entity.md:<<<<<<< HEAD
docs/design/entity.md:<<<<<<< HEAD
docs/design/entity.md:<<<<<<< HEAD
docs/design/entity.md:<<<<<<< HEAD
docs/design/entity.md:<<<<<<< HEAD
docs/design/init-mcir.puml:<<<<<<< HEAD

어느 순간 conflict 메시지가 소스코드에 포함된 듯하네요
@jihoon-seo 리포트 감사합니다.

2020-10-19 06:21 UTC, seokho-son commented
해당 메시지까지 일단 제가 정리해보도록 하겠습니다.
향후에 동작 여부 등 무결성 확인을 해주셔야할듯합니다~~

2020-10-19 06:41 UTC, jihoon-seo reviewed
커멘트 몇 개를 작성해 보았습니다.

2020-10-19 06:41 UTC, jihoon-seo commented on README.md
> +Learn how to start contribution on the [Contributing Guidline](https://github.com/cloud-barista/docs/tree/master/contributing)
```suggestion
Learn how to start contribution on the [Contributing Guideline](https://github.com/cloud-barista/docs/tree/master/contributing)
```

2020-10-19 06:41 UTC, jihoon-seo commented on src/core/model/node.go
> +	Name       string `json:"name"`
`src/core/model/cluster.go` 의 `type Cluster struct` 안에는 `Model` 이 남아 있는데
`src/core/model/node.go` 의 `type Node struct` 에서는 `Model` 을 삭제하신 이유가 혹시 무엇인지 알 수 있을까요?
(일관성 관련..)

2020-10-19 08:19 UTC, seokho-son commented
@itnpeople 코드에 들어가있는 conflict 메시지 및 내용을 제가 임의로 삭제하기 어렵네요.

docs/design/entity.md
docs/design/README.md
docs/design/init-mcir.puml

상기 파일 3개에 대한 사항만 점검하고 PR 업데이트하시면 되겠습니다.
`>>>>>>> Add base source code`
`<<<<<<< HEAD`
스트링이 있는 부분과, 정보 갱신이 필요합니다.

son@son:~/go/src/github.com/cloud-barista/cb-ladybug$ grep -r ">>>>>>> Add base source code"
docs/design/entity.md:>>>>>>> Add base source code
docs/design/entity.md:>>>>>>> Add base source code
docs/design/README.md:>>>>>>> Add base source code
docs/design/README.md:>>>>>>> Add base source code
docs/design/init-mcir.puml:>>>>>>> Add base source code

son@son:~/go/src/github.com/cloud-barista/cb-ladybug$ grep -r "<<<<<<< HEAD"
docs/design/entity.md:<<<<<<< HEAD
docs/design/entity.md:<<<<<<< HEAD
docs/design/entity.md:<<<<<<< HEAD
docs/design/entity.md:<<<<<<< HEAD
docs/design/entity.md:<<<<<<< HEAD
docs/design/entity.md:<<<<<<< HEAD
docs/design/entity.md:<<<<<<< HEAD
docs/design/entity.md:<<<<<<< HEAD
docs/design/entity.md:<<<<<<< HEAD
docs/design/entity.md:<<<<<<< HEAD
docs/design/entity.md:<<<<<<< HEAD
docs/design/entity.md:<<<<<<< HEAD
docs/design/entity.md:<<<<<<< HEAD
docs/design/entity.md:<<<<<<< HEAD
docs/design/init-mcir.puml:<<<<<<< HEAD

2020-10-20 01:51 UTC, itnpeople commented on docs/design/entity.md
> +        role: "control-plane",
이전에 잠시  <master or control-plane>  대해서 논의한 적이 있었는데 일단 control-plane 으로 쓰는 것으로 결정 했던 것 같습니다.

2020-10-20 01:52 UTC, jihoon-seo commented on docs/design/entity.md
> +        role: "control-plane",
네 알겠습니다.

2020-10-20 02:26 UTC, sykim-etri commented on docs/design/entity.md
> +        role: "control-plane",
관련하여 첨언 드리자면 과거 주로 master를 사용하다가 최근 control-plane로 바꾸어 사용하는 것으로 파악되었습니다.(예. K8s Cluster API)

2020-10-20 05:39 UTC, jihoon-seo commented
현재까지 나온 커멘트에 대해서는 모두 resolve 된 것으로 보입니다.

2020-10-20 05:44 UTC, seokho-son commented
저도 lgtm 입니다.

@sykim-etri 님께서 보시고 최종 머지하시면 되겠네요.. ^^

2020-10-20 10:29 UTC, sykim-etri requested changes

2020-10-20 10:29 UTC, sykim-etri commented on src/core/model/tumblebug/base.go
> +}
1. namespace의 필드명이 첫글자가 소문자인데, Name과 다른 특별한 이유가 있는건지요?
2. namespace의 json 태그는 없어도 무방한지요?
3. src/core/model/base.go에 정의된 Model과 혼동의 여지는 크지 않은지요?

2020-10-20 10:29 UTC, sykim-etri commented on src/core/model/tumblebug/mcis.go
> +		// 이부분은 향후 tumblebug 에서 수정해야 할듯
혹시 관련한 내용을 tumblebug에 전달되지 않았으면 이슈 등록을 해주시면 좋겠습니다.

2020-10-20 10:29 UTC, sykim-etri commented on src/rest-api/service/cluster.go
> +	WorkerNodeCount       int    `json:"workerNodeCount"`
최근 반영하신 json 스타일과의 차이 검토

2020-10-20 10:29 UTC, sykim-etri commented on src/core/model/cluster.go
> +	WorkerNodeCount       int    `json:"worker-node-count"`
tumblebug 등과 스타일이 달라서 논의가 필요할 것 같긴 합니다.

2020-10-20 10:29 UTC, sykim-etri commented on docs/test/README.md
> +▒ brew install jq           # mac os
가독성 측면에서 모든 ▒를 $ 등으로 대체하는 것이 좋아보입니다.

2020-10-20 23:39 UTC, itnpeople commented on src/docs/swagger.yaml
> +      operationId: DestroyCluster
일반적으로 create / destroy 로 쓰지 않나요?

2020-10-20 23:42 UTC, itnpeople commented on src/core/model/tumblebug/base.go
> +}
1~2 private 처리 해도 무방하기 때문에 그렇게 했습니다.
3. 현재는 동일하지만 향후  내용이 추가되거나 변동 될 수 있기 때문에 분리처리했습니다.

2020-10-20 23:46 UTC, itnpeople commented on docs/test/README.md
> +▒ brew install jq           # mac os
개인적으로는  $가 가독성이 좋지 못해서 일부러 ▒ 를 찾아서 썼습니다. 오히려 떨어지는 모양 이네요?

2020-10-21 00:11 UTC, itnpeople commented on src/docs/swagger.yaml
> +      operationId: DestroyCluster
클러스터인 경우 "create/destroy"
노드인 경우는 "insert/delete" 또는 "add/remove" 를 쓰는 것이 어떨지요

2020-10-21 00:15 UTC, itnpeople commented on src/core/model/cluster.go
> +	WorkerNodeCount       int    `json:"worker-node-count"`
일단 같이 공유했던 api 문서대로 하기는 했는데.. 논의 후 알려주세요.
소스코드 변경은 어렵지 않는데 UI 쪽에서는 문제 없을지..

2020-10-21 01:35 UTC, itnpeople commented on src/core/model/tumblebug/mcis.go
> +		// 이부분은 향후 tumblebug 에서 수정해야 할듯
/tumblebug/ns/<namespace>/mcis/<mcis name> 에서
0.2.0 버전에서 mcis 를 찾지 못했을 경우 http.statuscode 가 404를 리턴 해 주지 않았던 것으로 확인되었던것 같네요 
bugfix 되었을 지도 모르겠습니다.

2020-10-21 01:43 UTC, jihoon-seo commented on src/core/model/tumblebug/mcis.go
> +		// 이부분은 향후 tumblebug 에서 수정해야 할듯
[Tumblebug 현재 상황]
1. [`CoreGetMcisInfo`](https://github.com/cloud-barista/cb-tumblebug/blob/2f2091a2abb5e535a8feb5ba07ae5171eb655a39/src/core/mcis/control.go#L1317) 에서
`keyValue, _ := common.CBStore.Get(key)` 했는데
`keyValue == nil` 이면
`return nil, fmt.Errorf("Cannot find " + key)` 합니다.
2. [`RestGetMcis`](https://github.com/cloud-barista/cb-tumblebug/blob/2f2091a2abb5e535a8feb5ba07ae5171eb655a39/src/api/rest/server/mcis/control.go#L57) 에서
`result, err := mcis.CoreGetMcisInfo(nsId, mcisId)` 했는데
`err != nil` 이면
```
mapA := map[string]string{"message": err.Error()}
return c.JSON(http.StatusFailedDependency, &mapA)
```
합니다.

찾아 보니
`http.StatusFailedDependency` 는 424 입니다.

424 는 많이 안 쓰는 코드 같으므로
404 또는 500 을 리턴하도록 변경하겠습니다.

2020-10-21 01:45 UTC, jihoon-seo commented on src/core/model/tumblebug/mcis.go
> +		// 이부분은 향후 tumblebug 에서 수정해야 할듯
CB-Tumblebug repo에 이슈로 등록했습니다. (https://github.com/cloud-barista/cb-tumblebug/issues/280)

2020-10-21 02:12 UTC, sykim-etri commented on src/docs/swagger.yaml
> +      operationId: DestroyCluster
1. 클러스터의 경우
말씀하신 바와 같이 키워드로만 본다면 create/destroy로도 사용되긴 합니다만
관련 기술들인 EKS, GKE, AKE, kops 등에서는 create/delete 쌍으로 주로 사용하고 있어서.. create/delete가 더 익숙하게 느끼는 것 같습니다. 따라서 동일 도메인의 일반 키워드를 따라 가는 것이 바람직할 것 같습니다.
* https://docs.aws.amazon.com/ko_kr/eks/latest/userguide/create-cluster.html
* https://cloud.google.com/kubernetes-engine/docs/how-to/deleting-a-cluster?hl=ko
* https://docs.microsoft.com/ko-kr/rest/api/aks/managedclusters/delete

더불어 설명은 Delete a 
2. 노드의 경우
관련 기술들에서는 노드 풀 생성/삭제 방식으로 접근하고 있어서 참고할 만한 내용은 없어보입니다. 그래서 의미상  add/remove(선호)가 적합할 것 같습니다.

2020-10-21 02:59 UTC, sykim-etri commented on src/core/model/tumblebug/base.go
> +}
1번 문의는 naming convention 관련한 것으로, 혹시 namespace의 경우 특별히 다르게 하신 이유가 궁금합니다.

2020-10-21 03:03 UTC, sykim-etri commented on src/core/model/tumblebug/base.go
> +}
서연구원을 통해 naming convention과는 직접적인 연관이 없는 것을 확인하였습니다. 제가 Go가 익숙치 않다보니.^^

2020-10-21 03:20 UTC, itnpeople commented on src/core/model/tumblebug/base.go
> +}
다른 모듈에서 수정하지 못하도록 제약을 걸기위해서 소문자로 private 처리했습니다.
바꿀까요?

2020-10-21 03:54 UTC, sykim-etri commented on docs/test/README.md
> +▒ brew install jq           # mac os
$에는 명령 입력 프롬프트의 의미가 포함되다보니.. 더 적당하지 않을까 생각했습니다.

2020-10-21 03:56 UTC, sykim-etri commented on src/core/model/tumblebug/base.go
> +}
수정하지 않으셔도 될 것 같습니다. convention 측면만 생각하다가 Go의 특성을 놓쳤던 것 같습니다. unexport와 convention 이슈를 함께 해소할 방안은 잘 찾기 어렵네요.

2020-10-21 03:58 UTC, sykim-etri commented on src/core/model/cluster.go
> +	WorkerNodeCount       int    `json:"worker-node-count"`
cb-tumblebug, cb-spider도 통일되진 않은 상황으로 파악되었습니다. 정리가 되면 공유드리겠습니다.

2020-10-21 04:31 UTC, sykim-etri commented on src/core/model/cluster.go
> +	WorkerNodeCount       int    `json:"worker-node-count"`
저도 가독성면에선 현재 스타일이 더 나은 것 같습니다만.. 인터페이스 부분이라 통일하는 것이 바람직하겠습니다.

TB에서 관련 내용이 논의가 자체적으로는 진행되었던 사항이 있었는데, 제가 제대로 파악하지 못했었습니다. 기 논의된 바를 참조하여 LB에서도 camelCase(lower)로 진행하는 것이 향후 혼란이 덜할 것으로 생각됩니다.
번거로우시겠지만 변경을 부탁드립니다. 더불어 변경시 UI쪽 문제라면 어떤 것을 말씀하시는지요?
- https://github.com/cloud-barista/cb-tumblebug/pull/37#discussion_r337343692
- https://github.com/cloud-barista/cb-tumblebug/issues/125
- https://github.com/cloud-barista/cb-tumblebug/issues/180

2020-10-21 05:03 UTC, itnpeople commented on src/core/model/cluster.go
> +	WorkerNodeCount       int    `json:"worker-node-count"`
webtool 개발자분과  API  스펙 변경을  공유되어야 한다는 ... 
이미 개발하고 계실테니.. 아닐란가요

2020-10-21 06:21 UTC, sykim-etri commented on src/core/model/cluster.go
> +	WorkerNodeCount       int    `json:"worker-node-count"`
webtool쪽에는 별도로 통보하겠습니다. CB-Ladybug와 관련해서 본격적으로 API 작업을 하진 않은 상황입니다.

2020-10-21 06:46 UTC, sykim-etri commented on src/docs/swagger.json
> +                "controlPplaneNodeSpec": {
typo (controlPplaneNodeSpec -> controlPlaneNodeSpec)

2020-10-21 07:05 UTC, sykim-etri approved these changes

2020-10-21 08:22 UTC, merged